### ISSUE TITLE
Fond gris.

### ISSUE THREAD

**Issue by lionelmyszka** [jlethuau/wp-parallax-content-slider#12]
Bonjour,

Mon niveau technique n'étant pas très élevé, je compte sur votre indulgence :)
J'ai installé votre plugin sur mon blog Wordpress , mais le fond reste désespérément gris en mode "Résumé" et présente un aspect peu avenant en mode "Contenu complet". http://goo.gl/Yl4r4

J'utilise un thème de base : Twenty Ten by Wordpress

Pouvez-vous m'aider ?

Merci,

Lionel
06 82 49 59 18
webpatron.com

**Comment by jlethuau** [comment]
Bonjour,
le fond d'écran devrait changer en fonction du style choisi dans les réglages, ce n'est pas normal. Avez-vous bien modifié et validé les paramètres en choisissant un autre thème ? Avez-vous des erreurs dans la console ?

Pour le mode d'affichage du slider "page", c'est vraiment expérimental et ça a été ajouté pour que les gens qui ont vraiment des connaissances poussées en CSS, PHP, WP puisse modifier le code du plugin.

Dans la version courante, et tant que moi ou un cotributeur n'aura pas amélioré la chose, ca reste un mode peu utilisable :(
