### ISSUE TITLE
Howto: Add new Custom Themes

### ISSUE THREAD

**Issue by LukeTrout** [jlethuau/wp-parallax-content-slider#19]
Is there a way that we can create our own custom theme? I've modified one of the theme-XXX.css documents and inserted a line on the switch ($prix_slider_theme) function:
switch( $prlx_slider_theme )
        {
            case 'wood' :
                wp_enqueue_style( 'wp-parallax-content-slider-css-theme', plugins_url( 'css/theme-wood.css', **FILE** ) );

But I don't get the "Wood" option in the drop down menu.

Luke

**Comment by jlethuau** [comment]
Hi,
you'll have to add your option in the select box too and it should work.
See the main plugin file on line 600 : https://github.com/jlethuau/wp-parallax-content-slider/blob/master/wp-parallax-content-slider.php#L600
