### ISSUE TITLE
No Slider Admin link

### ISSUE THREAD

**Issue by LuckyLuciano** [jlethuau/wp-parallax-content-slider#21]
I love this slider, I installed the plugin and added the php to the page and your demo slides are working, however there is no Slider Admin link on the admin menu to change the slides.  What have I done wrong??

here is pic of my admin nav:

http://imgur.com/zfMzOU8

Please help cuz I love this slider.

**Comment by jlethuau** [comment]
Hi,
just go to the general Wordpress settings menu.
You'll see an extra link for WP Parallax Content Slider ;)

![image](https://f.cloud.github.com/assets/1629521/727056/3a1f90d2-e15f-11e2-94ca-5b9eb6b09f90.png)

**Comment by LuckyLuciano** [comment]
Never mind I got it worked out!! Thanks! Great plug in!! Love it!

**Comment by jlethuau** [comment]
OK, great! ;)
