### ISSUE TITLE
Link in slider

### ISSUE THREAD

**Issue by C4tApI** [jlethuau/wp-parallax-content-slider#24]
Hi!

I would like to know if it is possible to display links in the slider. Is there a code I can put in a file? If not, it would be a GREAT thing to add to your plugin.

Have a nice day! :)

**Comment by jlethuau** [comment]
Hi,
there is a way to do what you want by adding a filter to change the way Wordpress processes the exceprt: http://wordpress.org/support/topic/how-to-show-links-in-excerpt

I hope this will help you!
