### ISSUE TITLE
swipe is not a function, - Firebug?  

### ISSUE THREAD

**Issue by rydemods** [jlethuau/wp-parallax-content-slider#3]
jQuery(function() {
jQuery('#da-slider').cslider({
bgincrement : parseInt( prlx.bgincrement ),
autoplay : parseInt( prlx.autoplay ),
interval : parseInt( prlx.interval ),
current : parseInt( prlx.current )
});
jQuery('#da-slider').swipe({
swipeLeft: function() { jQuery('#da-slider').find('span.da-arrows-next').click() },
swipeRight: function() { jQuery('#da-slider').find('span.da-arrows-prev').click() },
})
});

just installed this latest version and firebug tells me line 11 Swipe is not a function ?.. 

not sure if this a majob problem or what?.

**Comment by jlethuau** [comment]
Hi, is it the only error you have in your console?

**Comment by rydemods** [comment]
Yep that was the only error i was getting..

On Sat, Apr 20, 2013 at 4:19 AM, Julien LE THUAUT
notifications@github.comwrote:

> Hi, is it the only error you have in your console?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jlethuau/wp-parallax-content-slider/issues/3#issuecomment-16677684
> .

## 

*Stevie Dean *
Web Designer
telephone: +82 (0)70-7893-2777
email:  stevie@seoulwebdesign.com

http://www.seoulwebdesign.com
