### ISSUE TITLE
How do I modify horizontal position of slide title, text and link

### ISSUE THREAD

**Issue by dan4berlin** [jlethuau/wp-parallax-content-slider#41]
Hi all,
this is a wonderful plugin and results are really eyecatching. 
Many thanks for providing it and doing so for free.

I have customized it for my website where I use it in static HTML mode but I can't find a way to move title, text and link (da-slide h2, da-slide p and da-link) independently to the right.
My goal is to have the three in centered alignment. Centered in relation to each other not centered in the slider (i.e.in the middle of it).
Any css I apply either has weird or no result at all. 
Can anybody help me with this and hint a solution?

Thanks in advance from Berlin.
Dan

**Comment by dan4berlin** [comment]
...found a solution myself.
In my case it is done with this css: 

width: 40%;  
position: absolute;
text-align: center;

in style.css

**Comment by jlethuau** [comment]
Great ;)
