### ISSUE TITLE
Cannot delete

### ISSUE THREAD

**Issue by funkster99** [jlethuau/wp-parallax-content-slider#49]
Hi, it's a nice plugin but I decided not to use it after all. Trouble is I can't delete it. Nothing happens when you click delete plugin, after you get to the list files to be deleted. Just a blank page, then when you return to plugin list it is still there. I have deleted files and folders in ftp area, but it is still listed in plugin list.

thanks for your help in letting me know about how to do this

**Comment by jlethuau** [comment]
I've found what causes the bug. V0.9.7 will fix the issue
