### ISSUE TITLE
Is is working on wordpress 3.9

### ISSUE THREAD

**Issue by filipmkd** [jlethuau/wp-parallax-content-slider#64]
I have installed this plugin on my test site, but it doesn't work perfectly, only shows last post although it is set to show last 5. 

Here is a preview: filiptest.esy.es/wordpress

**Comment by jlethuau** [comment]
Sorry for the delay!
It works great for me on all websites under wp3.9
The only issue I have to fix on this post limitation is dealing with sticky posts but that's another issue.
If you have any problem, maybe it comes from your theme or another plugin :(
