### ISSUE TITLE
WP Parallax Content Slider Bilingual Static Slider with Polylang plugin

### ISSUE THREAD

**Issue by RolandXII** [jlethuau/wp-parallax-content-slider#65]
Hello sirs and madames,

I'm a bit of a novice in php and wordpress.

How do I switch between 2 different language static sliders. (EN/CN)

I'm using the polylang plugin. Please help :(

BTW, great plugin!

Roland

**Comment by RolandXII** [comment]
Please sirs....help me. :(

**Comment by RolandXII** [comment]
HELP!!!!!

**Comment by jlethuau** [comment]
Hi,
sorry for the delay!
I've never had the experience of testing my plugin with the polylang plugin :(
I can only provide some help for WPML users but not for this one I'm sorry.
I hope there will be someone here to help you.

**Comment by RolandXII** [comment]
Hi jlethuau,

No worries. I managed to fix the issue.

For anyone who is facing similar predicament, do this:

Replace

include('static-slides-sample.php');

With

if(pll_current_language()=='en')
{ include('static-slides_mbh.php'); }

elseif(pll_current_language()=='en')
{ include('static-slides_mbh.php'); }

elseif(pll_current_language()=='zh')
{ include('static-slides_mbhCZ.php'); }

Where static-slides_mbhCZ is the translated language of your choice

Hope this helps everyone using polylang with parallax slider.

With folded hands,
Roland

**Comment by jlethuau** [comment]
Yeah,
you're a bit more than a PHP novice @RolandXII :smile:
