### ISSUE TITLE
Adding post data and featured image

### ISSUE THREAD

**Issue by jfarrugia1** [jlethuau/wp-parallax-content-slider#66]
Hi Guys,

I am using your slider and its pretty great. Id like to know how I can add post content to the h1 tags and the featured image of that post to the image source.

Im currently using HTML to display the content and images.

Id like to make this user freindly where they can just change the post content and featured image of that post to edit the slider.

Hopefully what im saying makes sense.

Thanks

**Comment by RolandXII** [comment]
Isn't that as simple as setting the "Slide display mode" to dynamic? Have you tried that?

**Comment by jlethuau** [comment]
Hi @jfarrugia90 
I think @RolandXII gave you the proper answer :)
