### ISSUE TITLE
How to set slider area

### ISSUE THREAD

**Issue by ahranchwi** [jlethuau/wp-parallax-content-slider#67]
how to put 'easy wp parallax slider' above of featured area at home page in Customizr theme?
![photo](https://cloud.githubusercontent.com/assets/8222578/4022653/94b8dd76-2b4d-11e4-9d96-8d9b575017df.jpg)

**Comment by jlethuau** [comment]
Hi,
can you tell me where exactly you've put the code?

**Comment by ahranchwi** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/8222578/4453103/e9649e00-4853-11e4-8f13-6b743dc06e9f.jpg)

**Comment by jlethuau** [comment]
Hi,
why do you use a php statement here?
Can't you just call the shortcode directly in tinyMCE?

Besides, what is that [epsshortcode]? My plugin declares only a [parallaxcontentslider] shortcode so I guess the shortcode you use is from another plugin. Maybe using mine, but not mine. 
I see EPS settings on your dashboard. Is this the plugin you use?

**Comment by jlethuau** [comment]
That's it. You don't use my plugin but this one: https://wordpress.org/plugins/easy-wp-parallax-slider/

So you should go to their plugin support page: http://support.oscitasthemes.com/

Regards
