### ISSUE TITLE
Autoplay mode shouldn´t stop

### ISSUE THREAD

**Issue by bergmedien** [jlethuau/wp-parallax-content-slider#9]
Hello!

The Parallax slider is great. Thx for this. I have one question of the function. The slides could be display in a auto-play mode. But when the user click on an arrow, the automatic function stops. Is this possible, that the slider go further, automatically? What should we do?

Best regards,
Gregor

**Comment by jlethuau** [comment]
Duplicated issue. See https://github.com/jlethuau/wp-parallax-content-slider/issues/6
